---
- name: compress files
  hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: compress
    archive:
       path:
       - /root/file1.txt
       - /usr/local/share/file2.txt
       - /var/log/lastlog
       dest: /root/files.tar.bz2
       format: bz2	 