---
- hosts: all
  gather_facts: no
  tasks:
    - name: stat module help to find the file info
      stat:
        path: /var/run
      register: your_variable

    - debug: var=your_variable.stat

    - shell: echo "{{ your_variable.stat }}" > /tmp/by_ansible