---
- name: gather facts
  hosts: all
  gather_facts: yes
  tasks:
    - name: alternative way to gather facts about remote host
      setup: filter='ansible_dist*'
      register: facts
    - debug: var=facts.ansible_facts.ansible_distribution
    - shell: echo "{{facts.ansible_facts.ansible_distribution}}" > /tmp/output.txt